################################
#     General configuration    #
################################
# locale: localization of your server
locale: en

# debug: whether to print debug info.
debug: false

# forward_mode: how Phenyl forward messages.
# Acceptable options:
#   sync - Sync all messages between QQ and Server.
#          %username% variable is *NOT AVAILABLE* for qq-to-server message under this mode . Use %nickname% instead.
#   command - Use `/ph say ~` on server and prefix in QQ to send message.
#   bind - Only messages from users that bound username and QQ number would be forwarded.
forward_mode: "bind"

# message_command: prefix of QQ messages to get forwarded to the server.
forward_prefix: "&"

# send_cross_server: whether to forward message between sub-servers.
send_cross_server: true

################################
#      Mirai configuration     #
################################

# user_id: your bot's QQ number.
user_id: 165420321

# user_pass: Your bot's QQ password.
# If you select ANDROID_PHONE as protocol, make sure your password length is less than 16.
user_pass: "12345654321"

# login_protocol: the protocol used to log in.
# Acceptable options: ANDROID_PHONE，ANDROID_PAD，ANDROID_WATCH. If meet problem logging in, try switch the protocol.
login_protocol: "ANDROID_PHONE"

# enabled_groups: the QQ groups you want to enable Phenyl.
enabled_groups:
    - 797717041
    - 958173932

################################
#   Database configuration     #
################################

# database: the kind of database you choose to store binding informations and chat messages.
# Acceptable options: sqlite, mysql, postgresql.
storage: "sqlite"

# If you chose sqlite above, ignore the following configs.
host: "127.0.0.1"
port: 3306
username: "root"
password: "123456"
database: "Phenyl"
table_prefix: "ph_"

################################
#   Message configuration      #
################################

# Available variables:
#   %server% - Your server name.
#   %sub_server% - Sub-server where the message sent.
#   %username% - Minecraft username.
#   %nickname% - Nickname in QQ group.
#   %message% - Message content.

# cross_sever_format: in-game cross server message format.
cross_sever_format: "[%sub_server]%username%:%message%"

# qq_to_server_format: format of QQ message forwarded to server.
# Use %nickname% instead of %username% if you selected sync mode.
qq_to_server_format: "[QQ]%username%:%message%"

# server_to_qq_format: format of server chat message forwarded to QQ.
server_to_qq_format: "%username%:%message%"

# on_join: message sent to QQ when players joined the game.
on_join: "%username% joined the game."

# on_switch: message sent to QQ when players switched from one sub-server to another.
on_switch: "%username% joined %sub_server%."

# on_leave: message sent to QQ when players left the game.
on_leave: "%username% left the game."

################################
#  Bungeecord configuration    #
################################

# server_alias: the alias of your bungee servers.
# If not set, Phenyl will use the server name.
server_alias:
    survival: "Survival"
    flat: "Flat"
    test: "Test"

# enabled_servers: the servers you want to enable message forwarding.
enabled_servers:
    - survival
    - flat
    - test

################################
#    Binding configuration     #
################################

# group_command: command sent in QQ groups to bind.
group_command: "#bind"

# confirm_command: command sent in QQ groups to confirm binding.
confirm_command: "#confirm"

# verification: the length of verification code. 0 to disable verifications.
verification: 6