name: Build Phenyl
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2.3.5
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          cache: "gradle"
          distribution: "temurin"
      - name: Change wrapper permission
        run: chmod +x ./gradlew
      - name: Build
        run: |
          ./gradlew jar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Phenyl
          path: build/libs/*.jar